import type { Edge, Node } from '@xyflow/react'
import type { DesignTokens } from './designTokens'
import type { HeatVariant } from './heatVariants'
import { kindForClassName } from './nodeKinds'

// Renders the current nodes/edges as a self-contained, static HTML/SVG
// snippet styled with the caller's own design tokens — no React Flow (or any
// JS) runtime required to display it, matching this project's "diagrams ship
// as imagery" philosophy.
const NODE_HEIGHT = 40
const CHAR_WIDTH = 7.5
const NODE_PADDING_X = 28
const CANVAS_MARGIN = 32

function nodeLabel(node: Node): string {
  return typeof node.data.label === 'string' ? node.data.label : ''
}

function nodeWidth(label: string): number {
  return Math.max(80, Math.round(label.length * CHAR_WIDTH) + NODE_PADDING_X)
}

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function edgeVariant(edge: Edge): HeatVariant {
  const variant = (edge.data as { variant?: HeatVariant } | undefined)?.variant
  return variant ?? 'default'
}

function edgeStroke(variant: HeatVariant, tokens: DesignTokens): { stroke: string; dashArray?: string } {
  if (variant === 'heat-flow' || variant === 'heat-static') return { stroke: tokens.primaryColor }
  if (variant === 'dashed') return { stroke: tokens.secondaryColor, dashArray: '6 6' }
  return { stroke: tokens.secondaryColor }
}

export function generateDiagramCode(nodes: Node[], edges: Edge[], tokens: DesignTokens): string {
  if (nodes.length === 0) {
    return '<!-- Diagram Lab: add nodes to the canvas before exporting code. -->'
  }

  const dims = new Map(nodes.map((node) => [node.id, { width: nodeWidth(nodeLabel(node)), height: NODE_HEIGHT }]))
  const minX = Math.min(...nodes.map((node) => node.position.x))
  const minY = Math.min(...nodes.map((node) => node.position.y))

  const nodeMarkup = nodes
    .map((node) => {
      const kind = kindForClassName(node.className)
      const { width, height } = dims.get(node.id)!
      const x = node.position.x - minX
      const y = node.position.y - minY
      const isActive = kind === 'active'
      const isDim = kind === 'dim'
      const borderColor = isActive ? tokens.primaryColor : tokens.secondaryColor
      const style = [
        'position:absolute',
        `left:${x}px`,
        `top:${y}px`,
        `width:${width}px`,
        `height:${height}px`,
        'display:flex',
        'align-items:center',
        'justify-content:center',
        `border:1px ${isDim ? 'dashed' : 'solid'} ${borderColor}`,
        'border-radius:8px',
        `font-family:${tokens.bodyFont}`,
        'font-size:13px',
        `opacity:${isDim ? 0.6 : 1}`,
        isActive ? `box-shadow:0 0 0 1px ${tokens.primaryColor}66` : '',
      ]
        .filter(Boolean)
        .join('; ')
      return `    <div style="${style}">${escapeHtml(nodeLabel(node))}</div>`
    })
    .join('\n')

  const edgeMarkup = edges
    .map((edge) => {
      const source = nodes.find((node) => node.id === edge.source)
      const target = nodes.find((node) => node.id === edge.target)
      if (!source || !target) return ''
      const sourceDim = dims.get(source.id)!
      const targetDim = dims.get(target.id)!
      const x1 = source.position.x - minX + sourceDim.width
      const y1 = source.position.y - minY + sourceDim.height / 2
      const x2 = target.position.x - minX
      const y2 = target.position.y - minY + targetDim.height / 2
      const { stroke, dashArray } = edgeStroke(edgeVariant(edge), tokens)
      const dashAttr = dashArray ? ` stroke-dasharray="${dashArray}"` : ''
      return `      <line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${stroke}" stroke-width="2"${dashAttr} />`
    })
    .filter(Boolean)
    .join('\n')

  const width = Math.round(Math.max(...nodes.map((node) => node.position.x - minX + dims.get(node.id)!.width))) + CANVAS_MARGIN
  const height =
    Math.round(Math.max(...nodes.map((node) => node.position.y - minY + dims.get(node.id)!.height))) + CANVAS_MARGIN

  return `<!-- Generated by Diagram Lab: static topology diagram, no JS runtime required. -->
<div style="position:relative; width:${width}px; height:${height}px; font-family:${tokens.headingFont};">
  <svg width="${width}" height="${height}" style="position:absolute; inset:0;">
${edgeMarkup}
  </svg>
${nodeMarkup}
</div>`
}

export async function copyDiagramCodeToClipboard(nodes: Node[], edges: Edge[], tokens: DesignTokens): Promise<void> {
  const code = generateDiagramCode(nodes, edges, tokens)
  await navigator.clipboard.writeText(code)
}
