import type { Edge, Node } from '@xyflow/react'
import type { DesignTokens } from './designTokens'
import { toPlainDiagram } from './exportDiagram'

// Generates a self-contained React Flow component that reproduces the
// canvas diagram *live* (animation, pan/zoom) in the consumer's own React
// app — the flagship export (specs/001-export-suite/contracts/component-export.md).
// Throws on empty input; the UI layer (useExportActions.ts) guards that case
// and shows a status label instead of calling this.
export function exportComponentCode(nodes: Node[], edges: Edge[], tokens: DesignTokens): { tsx: string; css: string } {
  if (nodes.length === 0) {
    throw new Error('Diagram Lab: add nodes to the canvas before exporting component code.')
  }

  const { nodes: plainNodes, edges: plainEdges } = toPlainDiagram(nodes, edges)

  const tsx = `// Generated by Diagram Lab — a self-contained React Flow component that
// reproduces this diagram live: animation keeps playing, pan/zoom works,
// styled only by the four tokens below (no Diagram Lab branding).
//
// Usage: copy this file + diagram.css into your project, install
// @xyflow/react, then render <Diagram /> inside an element with an explicit
// width/height (the .chiffon-diagram wrapper fills 100% of its parent).
import {
  ReactFlow,
  BaseEdge,
  ConnectionMode,
  Handle,
  Position,
  getBezierPath,
  type Edge,
  type EdgeProps,
  type Node,
  type NodeProps,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import './diagram.css'

const tokens = ${JSON.stringify(
    {
      primaryColor: tokens.primaryColor,
      secondaryColor: tokens.secondaryColor,
      headingFont: tokens.headingFont,
      bodyFont: tokens.bodyFont,
    },
    null,
    2,
  )}

const nodes: Node[] = ${JSON.stringify(plainNodes, null, 2)}

const edges: Edge[] = ${JSON.stringify(plainEdges, null, 2)}

// Renders the same four handles (top/bottom/left/right) the editor uses, so
// React Flow anchors sourceHandle/targetHandle identically here as on the
// canvas (contracts/edge-attachments.md). Hidden via diagram.css — exports
// never show connection points; they're only present so edges have
// something to anchor to.
function DiagramLabelNode({ data }: NodeProps) {
  const label = typeof data.label === 'string' ? data.label : ''
  const image = typeof data.image === 'string' ? data.image : undefined
  return (
    <>
      <Handle id="top" type="source" position={Position.Top} />
      <Handle id="bottom" type="source" position={Position.Bottom} />
      <Handle id="left" type="source" position={Position.Left} />
      <Handle id="right" type="source" position={Position.Right} />
      <div className="node-content">
        {image ? <img className="node-image" src={image} alt="" /> : null}
        <span className="node-label">{label}</span>
      </div>
    </>
  )
}

function DiagramHeatEdge({ id, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, data }: EdgeProps) {
  const [edgePath] = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY, targetPosition })
  const variant = (data as { variant?: string } | undefined)?.variant ?? 'default'
  const isHeat = variant === 'heat-flow' || variant === 'heat-static'
  const gradientId = \`chiffon-heat-gradient-\${id}\`
  return (
    <>
      {isHeat ? (
        <defs>
          <linearGradient id={gradientId} gradientUnits="userSpaceOnUse" x1={sourceX} y1={sourceY} x2={targetX} y2={targetY}>
            <stop offset="0%" stopColor="var(--token-primary)" />
            <stop offset="100%" stopColor="var(--token-primary)" />
          </linearGradient>
        </defs>
      ) : null}
      <BaseEdge id={id} path={edgePath} className={\`edge edge-\${variant}\`} style={isHeat ? { stroke: \`url(#\${gradientId})\` } : undefined} />
    </>
  )
}

const nodeTypes = { labelNode: DiagramLabelNode }
const edgeTypes = { heat: DiagramHeatEdge }

export default function Diagram() {
  return (
    <div
      className="chiffon-diagram"
      style={
        {
          '--token-primary': tokens.primaryColor,
          '--token-secondary': tokens.secondaryColor,
          '--token-heading-font': tokens.headingFont,
          '--token-body-font': tokens.bodyFont,
        } as React.CSSProperties
      }
    >
      <ReactFlow
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        edgeTypes={edgeTypes}
        connectionMode={ConnectionMode.Loose}
        fitView
        panOnDrag
        zoomOnScroll
        zoomOnPinch
        nodesDraggable={false}
        nodesConnectable={false}
        elementsSelectable={false}
        preventScrolling={false}
      />
    </div>
  )
}
`

  const css = `/* Generated by Diagram Lab — mirrors the canvas treatments this diagram was
   authored with. Every color/font reads from a --token-* custom property set
   inline by Diagram.tsx, so editing the tokens there restyles this diagram
   without touching this file. */
.chiffon-diagram {
  position: relative;
  width: 100%;
  height: 100%;
}

/* Connection handles exist only so edges have somewhere to anchor — this
   export never lets a viewer create or drag a connection, so the handles
   themselves are never shown. */
.chiffon-diagram .react-flow__handle {
  opacity: 0;
  pointer-events: none;
}

.chiffon-diagram .node {
  cursor: default;
  padding: 10px 14px;
  border-radius: 8px;
  border: 1px solid var(--token-secondary, #ccc);
  background: #fff;
  color: inherit;
  font-family: var(--token-body-font, sans-serif);
  font-size: 13px;
  text-align: center;
  box-sizing: border-box;
}

.chiffon-diagram .node-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6px;
  width: 100%;
  height: 100%;
  overflow: hidden;
}

.chiffon-diagram .node-label {
  flex: 0 0 auto;
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-family: var(--token-heading-font, sans-serif);
}

.chiffon-diagram .node-image {
  flex: 1 1 28px;
  min-width: 0;
  min-height: 0;
  width: auto;
  max-width: 100%;
  object-fit: contain;
  border-radius: 6px;
  background: #fff;
  padding: 3px;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.12);
}

.chiffon-diagram .node-active {
  border-color: var(--token-primary, #666);
  box-shadow: 0 0 0 1px color-mix(in srgb, var(--token-primary, #666) 40%, transparent);
}

.chiffon-diagram .node-dim {
  color: rgba(0, 0, 0, 0.55);
  border-style: dashed;
}

.chiffon-diagram .edge-heat-flow {
  stroke-width: 2.5;
  stroke-dasharray: 6 6;
  animation: chiffon-heat-flow 0.7s linear infinite;
  filter: drop-shadow(0 0 3px color-mix(in srgb, var(--token-primary, #666) 55%, transparent));
}

.chiffon-diagram .edge-heat-static {
  stroke-width: 2.5;
}

.chiffon-diagram .edge-dashed {
  stroke: var(--token-secondary, #ccc);
  stroke-dasharray: 4 4;
}

.chiffon-diagram .edge-default {
  stroke: var(--token-secondary, #ccc);
}

@keyframes chiffon-heat-flow {
  from {
    stroke-dashoffset: 24;
  }
  to {
    stroke-dashoffset: 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .chiffon-diagram .edge-heat-flow {
    animation: none;
  }
}
`

  return { tsx, css }
}

// Clipboard form for the "Export component" button: both files concatenated
// with marker comments so they're splittable by eye or by a coding agent
// (contracts/component-export.md "Clipboard form").
export function componentCodeSnippet(nodes: Node[], edges: Edge[], tokens: DesignTokens): string {
  const { tsx, css } = exportComponentCode(nodes, edges, tokens)
  return `/* ─── diagram.css */\n${css}\n// ─── Diagram.tsx\n${tsx}`
}

export async function copyComponentCodeToClipboard(nodes: Node[], edges: Edge[], tokens: DesignTokens): Promise<void> {
  const snippet = componentCodeSnippet(nodes, edges, tokens)
  await navigator.clipboard.writeText(snippet)
}
